### ISSUE TITLE
Installing naether gem fails

### ISSUE THREAD

**Issue by kkebb** [mguymon/naether#23]
Command used to install naether
```
java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install naether
```

ERROR:
```
Building native extensions.  This could take a while...
ERROR:  Error installing naether:
	ERROR: Failed to build gem native extension.

    "java -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar" -rubygems file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/gems/shared/gems/rake-10.1.0/bin/rake RUBYARCHDIR=/opt/logstash/vendor/bundle/jruby/1.9/gems/naether-0.14.2-java/lib RUBYLIBDIR=/opt/logstash/vendor/bundle/jruby/1.9/gems/naether-0.14.2-java/lib
/bin/sh: java -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar: No such file or directory


Gem files will remain installed in /opt/logstash/vendor/bundle/jruby/1.9/gems/naether-0.14.2-java for inspection.
Results logged to /opt/logstash/vendor/bundle/jruby/1.9/gems/naether-0.14.2-java/./gem_make.out
```
Is there anything else that needs to be configured in my environment before installing this gem?
here are some of the env variables I have defined:
```
GEM_HOME=vendor/bundle/jruby/1.9
GEM_PATH=""
```

**Comment by efi** [comment]
Was there any progress regarding this issue?

Any workarounds?

**Comment by kkebb** [comment]
Unfortunately, I haven't pursued this issue, still waiting on a response although, I think we chose to go with a newer version of logstash.

**Comment by mguymon** [comment]
Sorry, this somehow flow under my radar.  The gem install uses a Rakefile extension to install the jar dependencies, looks like it is failing trying to run the rake embedded in the jar.  Looks like it is expanding the path to `/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar` which doe not exist?

**Comment by mguymon** [comment]
Could add an ENV to disable the post install and add a bin to manually install them.

**Comment by mguymon** [comment]
Closing for now, if you have any continuing issues installing go ahead and reopen.
