### ISSUE TITLE
Update gem dependency on rjb

### ISSUE THREAD

**Issue by r6p** [mguymon/naether#24]
Currently the gem dependency for rjb is set to rjb (~> 1.4.0). Since rjb has moved ahead in time naether now conflicts with other gems in our Gemfile like buildr which uses rjb (=1.5.1). It would be nice if the naether dependency on rjb would be upgraded to ~> 1.5.0. Thanks!

**Comment by mguymon** [comment]
Ill do some test and see if it is safe to loosen the version to < 1.6, > 1.4

**Comment by mguymon** [comment]
released 0.14.3 that allows rjb from 1.4 to 1.5
