### ISSUE TITLE
Parent Pom

### ISSUE THREAD

**Issue by ecmel** [mguymon/naether#25]
Hi,

I am trying to get dependencies for a stock Spring Boot pom.xml (which refrences a parent pom):

```
Naether naether = new NaetherImpl();

naether.addDependencies("C:\\Users\\ecmel\\Documents\\NetBeansProjects\\demo\\pom.xml");

naether.resolveDependencies(true);

System.out.println(naether.getResolvedClassPath());
```

I got this error:

```
Exception in thread "main" com.tobedevoured.naether.maven.ProjectException: Failed to build project from pom
    at com.tobedevoured.naether.maven.Project.loadPOM(Project.java:123)
    at com.tobedevoured.naether.maven.Project.<init>(Project.java:85)
    at com.tobedevoured.naether.impl.NaetherImpl.addDependencies(NaetherImpl.java:325)
    at com.tobedevoured.naether.impl.NaetherImpl.addDependencies(NaetherImpl.java:291)
    at com.mycompany.mavenproject1.Main.main(Main.java:25)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
Non-readable POM C:\Users\ecmel\Documents\NetBeansProjects\demo: C:\Users\ecmel\Documents\NetBeansProjects\demo (Access is denied) @ 
```

POM

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>demo</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.6.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>
```

**Comment by mguymon** [comment]
Looks like the issue is with the empty `<relativePath/> <!-- lookup parent from repository -->`. Naether loads the relative poms based on the path. Will have to investigate how the pom handles a relative path based on the repository.

**Comment by mguymon** [comment]
@ecmel can you try 0.15.2 to see if it fixes your issue?

    <dependency>
      <groupId>com.tobedevoured.naether</groupId>
      <artifactId>core</artifactId>
      <version>0.15.2</version>
    </dependency>


... the maven repo refuses to let me deploy snapshots, so am stuck using minors for now.

**Comment by mguymon** [comment]
@ecmel Ok turns out I did it the hard way before I realized the main issue was [setting remote repositories](https://github.com/mguymon/naether/commit/41843f53488c0d13bd0904b2523ced8c4098467f) when the Maven Project is being inspected

Can you test out 0.15.3 to see if it fixes your problem?

    <dependency>
      <groupId>com.tobedevoured.naether</groupId>
      <artifactId>core</artifactId>
      <version>0.15.3</version>
    </dependency>

**Comment by ecmel** [comment]
@mguymon Tried 0.15.2 and it works :+1: 

Can't get 0.15.3 from maven repository yet but will try that too.

**Comment by mguymon** [comment]
@ecmel the 0.15.2 works if you have a local copy of the parent. On a fresh install it fails, because it does not look at remote repos, that is what 0.15.3 fixes.

**Comment by ecmel** [comment]
@mguymon  0.15.3 works both with local copy and fresh install.

Thank you for the great library.

Using a Project class also works for both cases if I use the full constructor:
```
    Naether n = new NaetherImpl();
    Project p = new Project("C:\\Users\\ecmel\\Projects\\demo\\pom.xml", n.getLocalRepoPath(), n.getRemoteRepositories());    
    n.addDependencies(p);
    n.resolveDependencies(true);
    System.out.println(n.getResolvedClassPath());
```

I am not sure though, if this is the correct usage.

I need to access Project for obtaining other information about POM.

**Comment by mguymon** [comment]
@ecmel  awesome, I love hearing that Naether has been helpful.

You are using the `Project` correctly. If you using the `new Project("pom.xml")` constructor, it will use your defauIt local repo, but does *not* use the default remote repos. I built most of the Maven helper classes for internal use and did not really flush out or document their APIs well.
