### ISSUE TITLE
Update the default maven repo

### ISSUE THREAD

**Issue by ramarnat** [mguymon/naether#34]
Http is no longer allowed, and the current default url goes to a 501. See https://support.sonatype.com/hc/en-us/articles/360041287334

We can use NAETHER_MIRROR to override, but may also be good to publish an update for the default?

**Comment by mguymon** [comment]
Yeah, sure push an update. Easy enough to do, i will try and get to it later today.

**Comment by mguymon** [comment]
I release 0.15.6 with the https changes, give it a whirl

**Comment by ramarnat** [comment]
For some reason bundler is resolving the rjb dependency under java

```n Gemfile:
  fluentdsf_extractor was resolved to 0.2.8.4, which depends on
    full360-helpers was resolved to 0.0.12, which depends on
      lock_jar was resolved to 0.15.2, which depends on
        naether was resolved to 0.15.6, which depends on
          rjb```

**Comment by ramarnat** [comment]
Ah, no java version published to rubygems. I also found that rake is needed even if not development.

**Comment by mguymon** [comment]
:facepalm: pushed the missing java gem

**Comment by mguymon** [comment]
release 0.15.7 that puts rake a dep
